# Generated by Django 5.0.4 on 2024-06-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_sku_alter_variant_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
